global using System;
global using System.Collections;
global using System.Collections.Generic;
global using System.Globalization;
global using System.IO;
global using System.Linq;
global using System.Reflection;
global using System.Text;
global using System.Text.Json;
global using System.Text.Json.Serialization;
global using System.Threading;
global using Autodesk.Revit.DB;
global using Autodesk.Revit.DB.Architecture;
global using Autodesk.Revit.DB.Electrical;
global using Autodesk.Revit.DB.ExtensibleStorage;
global using Autodesk.Revit.DB.Mechanical;
global using Autodesk.Revit.DB.Plumbing;
global using Autodesk.Revit.DB.Structure;
global using Autodesk.Revit.UI;
global using View = Autodesk.Revit.DB.View;
global using Autodesk.Revit.ApplicationServices;
global using Autodesk.Revit.Attributes;
global using WpfPoint = System.Windows.Point;
global using WpfRect = System.Windows.Rect;
global using WpfColor = System.Windows.Media.Color;
global using WpfImageSource = System.Windows.Media.ImageSource;
global using WpfDrawingGroup = System.Windows.Media.DrawingGroup;
global using WpfDrawingContext = System.Windows.Media.DrawingContext;
global using WpfSolidColorBrush = System.Windows.Media.SolidColorBrush;
global using WpfPen = System.Windows.Media.Pen;
global using WpfBrushes = System.Windows.Media.Brushes;
global using WpfPenLineCap = System.Windows.Media.PenLineCap;
global using WpfDrawingImage = System.Windows.Media.DrawingImage;
global using WpfFormattedText = System.Windows.Media.FormattedText;
global using WpfFlowDirection = System.Windows.FlowDirection;
global using WpfTypeface = System.Windows.Media.Typeface;
global using FormsTimer = System.Windows.Forms.Timer;
